FROM python:3.10.6

LABEL version="v1.0.0"
LABEL description="project"

RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install python3-pip -y
RUN pip install --upgrade pip

WORKDIR /data/app
COPY . .

RUN pip install -r requirements.txt 
CMD ["python", "main.py"]
